"""Indexing done.

Revision ID: 047f5b401059
Revises: 3f6a3ee3525f
Create Date: 2023-01-26 03:20:01.595437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '047f5b401059'
down_revision = '3f6a3ee3525f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cells_geo_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cells_geo_ids_id'), ['id'], unique=False)

    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_geo_ids_id'), ['id'], unique=False)

    with op.batch_alter_table('s2_cell_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_s2_cell_tokens_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('s2_cell_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_s2_cell_tokens_id'))

    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_geo_ids_id'))

    with op.batch_alter_table('cells_geo_ids', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cells_geo_ids_id'))

    # ### end Alembic commands ###
