"""geo_ids_add_boundary_type

Revision ID: 2742e8bafcc6
Revises: c6dac956003a
Create Date: 2023-05-05 02:06:35.802651

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2742e8bafcc6'
down_revision = 'c6dac956003a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('boundary_type', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.drop_column('boundary_type')

    # ### end Alembic commands ###
