"""Authority token added for GeoIds table

Revision ID: 3f6a3ee3525f
Revises: 4bd1635efeb9
Create Date: 2023-01-18 06:26:20.957640

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f6a3ee3525f'
down_revision = '4bd1635efeb9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('authority_token', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.drop_column('authority_token')

    # ### end Alembic commands ###
