"""add_country_with_GeoIds_table

Revision ID: c6dac956003a
Revises: db431b90937d
Create Date: 2023-03-18 03:09:40.347010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6dac956003a'
down_revision = 'db431b90937d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.add_column(sa.Column('country', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('geo_ids', schema=None) as batch_op:
        batch_op.drop_column('country')

    # ### end Alembic commands ###
