"""Lookup tables migration. Geo Ids, Cell Ids, Middle table.

Revision ID: d48fb18842aa
Revises: 
Create Date: 2022-12-17 22:33:29.094348

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd48fb18842aa'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('geo_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.String(), nullable=True),
    sa.Column('geo_data', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('geo_id')
    )
    op.create_table('s2_cell_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cell_token', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cell_token')
    )
    op.create_table('cells_geo_ids',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('geo_id', sa.Integer(), nullable=True),
    sa.Column('cell_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['cell_id'], ['s2_cell_tokens.id'], ),
    sa.ForeignKeyConstraint(['geo_id'], ['geo_ids.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('cells_geo_ids')
    op.drop_table('s2_cell_tokens')
    op.drop_table('geo_ids')
    # ### end Alembic commands ###
